services:
  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    restart: always
    environment:
      POSTGRES_USER: sentinel_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: sentinel_core
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
