"""add_scan_tables

Revision ID: 7a0334cdb03c
Revises: 1f78d93e9317
Create Date: 2026-04-06 16:01:10.280177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0334cdb03c'
down_revision: Union[str, Sequence[str], None] = '1f78d93e9317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_packages', sa.Integer(), nullable=False),
    sa.Column('scanned_packages', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    op.create_index('ix_scan_jobs_owner_repo', 'scan_jobs', ['owner', 'repo_name'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=512), nullable=False),
    sa.Column('package_version', sa.String(length=255), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('malware_status', sa.String(length=50), nullable=False),
    sa.Column('malware_score', sa.Float(), nullable=True),
    sa.Column('scanner_version', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], name=op.f('fk_scan_results_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_results'))
    )
    op.create_index('ix_scan_results_job_id', 'scan_results', ['job_id'], unique=False)
    op.create_index('ix_scan_results_package', 'scan_results', ['package_name', 'package_version', 'ecosystem'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_results_package', table_name='scan_results')
    op.drop_index('ix_scan_results_job_id', table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index('ix_scan_jobs_owner_repo', table_name='scan_jobs')
    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
